### ISSUE TITLE
Notice: unable to reach https://admin:password@host:4516/deployit. The error is: RESTEASY003210: Could not find resource for full path: https://host:port/deployit

### ISSUE THREAD

**Issue by anamika876** [xebialabs-community/puppet-xldeploy#134]

**Comment by anamika876** [comment]
XL Deploy version is 6.1.0. And I am not able to connect Rest services provided by XL Deploy. Can anyone help me in this.

**Comment by jdewinne** [comment]
When are you getting this error message? Also, did you configure the `http_server_address`?

**Comment by anamika876** [comment]
Hi,

I am trying to connect XL deploy with Jenkins. Test Connection issuing the error:
XL Deploy configuration is not valid! com.xebialabs.deployit.ci.DeployitPluginException: java.lang.IllegalStateException: Could not contact the server at https://host:port/deployit

I tried to browse the URL https://host:port/deployit
RESTEASY003210: Could not find resource for full path: https://host:port/deployit

Let me know if you have solution for this.

Regards,
Anamika

**Comment by jdewinne** [comment]
> I am trying to connect XL deploy with Jenkins.

Is this actually related to Puppet? Or are you using the [Jenkins plugin](https://wiki.jenkins-ci.org/display/JENKINS/XL+Deploy+Plugin)?

**Comment by anamika876** [comment]
Sorry this is not related to Puppet. I am using XL deploy plugin in Jenkins to communicate with XL deploy and proceed with the deployment. However it is not connecting with Jenkins.

**Comment by jdewinne** [comment]
In that case I think you should contact [XebiaLabs support](http://support.xebialabs.com). Closing this issue.
